# try:
#     numerator = 10
#     denominator = 0

#     result = numerator/denominator
#     print(result)
# except:
#     print("error:denominator cannot be 0")

# try:
#     print(X)
# except NameError:
#     print("an exception occured")
# except:
#     print("x is not defined")

# try:
#     print("hello")
# except:
#     print("something wentwrong")
# else:
#     print("nothing went wrong")

# try:
#     print(x)
# except:
#     print("something went wrong")
# finally:
#     print("the'try except'is finished")        